# Generated by Django 3.0.6 on 2020-06-02 19:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Ask_IT', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useradditional',
            name='avatar',
        ),
        migrations.AddField(
            model_name='useradditional',
            name='department',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
    ]
