# Generated by Django 3.0.6 on 2020-06-02 19:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Ask_IT', '0002_auto_20200602_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useradditional',
            name='department',
        ),
        migrations.AddField(
            model_name='useradditional',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
