# Generated by Django 3.0.6 on 2020-06-02 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('Ask_IT', '0003_auto_20200602_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useradditional',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars'),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ask_IT.Category')),
            ],
        ),
    ]
