# Generated by Django 3.0.6 on 2020-06-02 21:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Ask_IT', '0004_auto_20200602_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.TextField(default='', max_length=100),
        ),
    ]
