# Generated by Django 3.0.6 on 2020-06-02 21:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('Ask_IT', '0005_auto_20200602_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
    ]
