# Generated by Django 3.0.6 on 2020-06-02 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('Ask_IT', '0007_category_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ask_IT.Category'),
        ),
    ]
