# Generated by Django 3.0.6 on 2020-06-10 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ask_IT', '0008_auto_20200602_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Ask_IT.Category'),
        ),
    ]
