# Generated by Django 3.0.6 on 2020-06-11 21:27

import django.db.models.deletion
import precise_bbcode.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Ask_IT', '0009_auto_20200611_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='description',
        ),
        migrations.AddField(
            model_name='question',
            name='_content_rendered',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='content',
            field=precise_bbcode.fields.BBCodeTextField(default='', no_rendered_field=True),
        ),
        migrations.CreateModel(
            name='BestAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ask_IT.Answer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ask_IT.Question')),
            ],
        ),
    ]
