# Generated by Django 3.0.6 on 2020-07-03 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Ask_IT', '0011_auto_20200702_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestanswer',
            name='answer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bestanswerr', to='Ask_IT.Answer'),
        ),
        migrations.AlterField(
            model_name='bestanswer',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bestanswer', to='Ask_IT.Question'),
        ),
        migrations.AlterField(
            model_name='useradditional',
            name='avatar',
            field=models.ImageField(blank=True, default='Ask_IT/img/default_avatar.png', null=True, upload_to='avatars'),
        ),
        migrations.AlterField(
            model_name='useradditional',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
