# Generated by Django 3.0.6 on 2020-07-03 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ask_IT', '0012_auto_20200703_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='numberOfResponses',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bestanswer',
            name='answer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Ask_IT.Answer'),
        ),
        migrations.CreateModel(
            name='LastAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Ask_IT.Answer')),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lastanswer', to='Ask_IT.Question')),
            ],
        ),
    ]
